import Resort from "../types/resort";

const resorts: Resort[] = [
  {
    id: 0,
    name: "49 Degrees North",
    img: "./images/49-degrees-north.png",
    state: "Washington",
    region: "Northwest",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 1,
    name: "Alta",
    img: "./images/alta.png",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1991,
  },
  {
    id: 2,
    name: "Alyeska",
    img: "./images/alyeska.png",
    state: "Alaska",
    region: "Northwest",
    country: "US",
    yearPainted: 2009,
  },
  {
    id: 3,
    name: "Antelope Butte",
    img: "./images/antelope-butte.png",
    state: "Wyoming",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1996,
  },
  {
    id: 4,
    name: "Arapahoe Basin",
    img: "./images/arapahoe-basin.png",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1991,
  },
  {
    id: 5,
    name: "Ascutney",
    img: "./images/ascutney.png",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 2003,
  },
  {
    id: 6,
    name: "Aspen Highlands",
    img: "./images/aspen-highlands.png",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1994,
  },
  {
    id: 7,
    name: "Bear Mountain",
    img: "./images/bear-mountain.png",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1988,
  },
  {
    id: 8,
    name: "Beaver Mountain",
    img: "./images/beaver-mountain.png",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2011,
  },
  {
    id: 9,
    name: "Big Sky",
    img: "./images/big-sky.png",
    state: "Montana",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2014,
  },
  {
    id: 10,
    name: "Bogus Basin",
    img: "./images/bogus-basin.png",
    state: "Idaho",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2010,
  },
  {
    id: 11,
    name: "Boreal",
    img: "./images/boreal.png",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1987,
  },
  {
    id: 12,
    name: "Boyne Highlands",
    img: "./images/boyne-highlands.png",
    state: "Michigan",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 1988,
  },
  {
    id: 13,
    name: "Boyne",
    img: "./images/boyne.png",
    state: "Michigan",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2003,
  },
  {
    id: 14,
    name: "Breckenridge",
    img: "./images/breckenridge.png",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2016,
  },
  {
    id: 15,
    name: "Bretton Woods",
    img: "./images/bretton-woods.png",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 16,
    name: "Bridger Bowl",
    img: "./images/bridger-bowl.png",
    state: "Montana",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2005,
  },
  {
    id: 17,
    name: "Brighton",
    img: "./images/brighton.png",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1999,
  },
  {
    id: 18,
    name: "Bristol Mountain",
    img: "./images/bristol-mountain.png",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2011,
  },
  {
    id: 19,
    name: "Bromley",
    img: "./images/bromley.png",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 20,
    name: "Brundage",
    img: "./images/brundage.png",
    state: "Idaho",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 21,
    name: "Calabogie",
    img: "./images/calabogie.png",
    state: "Ontario",
    region: "Ontario",
    country: "Canda",
    yearPainted: 2013,
  },
  {
    id: 22,
    name: "Camelback",
    img: "./images/camelback.png",
    state: "Pennsylvania",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2008,
  },
  {
    id: 23,
    name: "Cannon Mountain",
    img: "./images/cannon-mountain.png",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 24,
    name: "Cardrona",
    img: "./images/cardrona.png",
    state: "",
    region: "",
    country: "New Zealand",
    yearPainted: 2018,
  },
  {
    id: 25,
    name: "Cataloochee",
    img: "./images/cataloochee.png",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2010,
  },
  {
    id: 26,
    name: "Cloudcroft",
    img: "./images/cloudcroft.png",
    state: "New Mexico",
    region: "Southwest",
    country: "US",
    yearPainted: 2016,
  },
  {
    id: 27,
    name: "Cooper Mountain",
    img: "./images/cooper-mountain.png",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2011,
  },
  {
    id: 28,
    name: "Copper Mountain",
    img: "./images/copper-mountain.png",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2018,
  },
  {
    id: 29,
    name: "Coronet Peak",
    img: "./images/coronet-peak.png",
    state: "",
    region: "",
    country: "New Zealand",
    yearPainted: 1990,
  },
  {
    id: 30,
    name: "Cottonwood Canyon",
    img: "./images/cottonwood-canyon.png",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2001,
  },
  {
    id: 31,
    name: "Cranmore",
    img: "./images/cranmore.png",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 32,
    name: "Crested Butte",
    img: "./images/crested-butte.png",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1991,
  },
  {
    id: 33,
    name: "Crotched",
    img: "./images/crotched.png",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2004,
  },
  {
    id: 34,
    name: "Crystal",
    img: "./images/crystal.png",
    state: "Washington",
    region: "Northwest",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 35,
    name: "Deer Valley",
    img: "./images/deer-valley.png",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 36,
    name: "Devil's Head",
    img: "./images/devil's-head.png",
    state: "Wisconsin",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2008,
  },
  {
    id: 37,
    name: "Discovery Ski Area",
    img: "./images/discovery-ski-area.png",
    state: "Montana",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 1993,
  },
  {
    id: 38,
    name: "Dodge Ridge",
    img: "./images/dodge-ridge.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2010,
  },
  {
    id: 39,
    name: "Eagle Point",
    img: "./images/eagle-point.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2010,
  },
  {
    id: 40,
    name: "Eaglecrest",
    img: "./images/eaglecrest.png",
    state: "Alaska",
    region: "Northwest",
    country: "US",
    yearPainted: 2009,
  },
  {
    id: 41,
    name: "Eldora",
    img: "./images/eldora.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1997,
  },
  {
    id: 42,
    name: "Falls Creek",
    img: "./images/falls-creek.jpg",
    state: "",
    region: "",
    country: "Austrialia",
    yearPainted: 2005,
  },
  {
    id: 43,
    name: "Grand Targhee",
    img: "./images/grand-targhee.jpg",
    state: "Wyoming",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2001,
  },
  {
    id: 44,
    name: "Grouse Mountain",
    img: "./images/grouse-mountain.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2001,
  },
  {
    id: 45,
    name: "Gunstock",
    img: "./images/gunstock.jpg",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2017,
  },
  {
    id: 46,
    name: "Heavenly",
    img: "./images/heavenly.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2003,
  },
  {
    id: 47,
    name: "Holiday Valley",
    img: "./images/holiday-valley.jpg",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 48,
    name: "Hotham",
    img: "./images/hotham.jpg",
    state: "",
    region: "",
    country: "Austrialia",
    yearPainted: 2005,
  },
  {
    id: 49,
    name: "Hunter Mountain",
    img: "./images/hunter-mountain.jpg",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2018,
  },
  {
    id: 50,
    name: "Jackson Hole",
    img: "./images/jackson-hole.png",
    state: "Wyoming",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2015,
  },
  {
    id: 51,
    name: "Jay Peak",
    img: "./images/jay-peak.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 2017,
  },
  {
    id: 52,
    name: "Keystone",
    img: "./images/keystone.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1991,
  },
  {
    id: 53,
    name: "Kicking Horse",
    img: "./images/kicking-horse.jpg",
    state: "",
    region: "British Columbia",
    country: "US",
    yearPainted: 2000,
  },
  {
    id: 54,
    name: "Killington",
    img: "./images/killington.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 55,
    name: "Kirkwood",
    img: "./images/kirkwood.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1989,
  },
  {
    id: 56,
    name: "Kopaonik",
    img: "./images/kopaonik.jpg",
    state: "",
    region: "",
    country: "Serbia",
    yearPainted: 2009,
  },
  {
    id: 57,
    name: "Lake Louise",
    img: "./images/lake-louise.jpg",
    state: "",
    region: "Alberta",
    country: "Canada",
    yearPainted: 2012,
  },
  {
    id: 58,
    name: "Liberty",
    img: "./images/liberty.jpg",
    state: "Pennsylvania",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2002,
  },
  {
    id: 59,
    name: "Loon",
    img: "./images/loon.jpg",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2011,
  },
  {
    id: 60,
    name: "Loveland",
    img: "./images/loveland.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 61,
    name: "Mammoth",
    img: "./images/mammoth.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2008,
  },
  {
    id: 62,
    name: "Massanutten",
    img: "./images/massanutten.jpg",
    state: "Virginia",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2002,
  },
  {
    id: 63,
    name: "Mission Ridge",
    img: "./images/mission-ridge.jpg",
    state: "Washington",
    region: "Northwest",
    country: "US",
    yearPainted: 2005,
  },
  {
    id: 64,
    name: "Monarch",
    img: "./images/monarch.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 65,
    name: "Mont Blanc",
    img: "./images/mont-blanc.jpg",
    state: "",
    region: "Quebec",
    country: "Canada",
    yearPainted: 2010,
  },
  {
    id: 66,
    name: "Montana Snowbowl",
    img: "./images/montana-snowbowl.jpg",
    state: "Montana",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2017,
  },
  {
    id: 67,
    name: "Mount Snow",
    img: "./images/mount-snow.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 68,
    name: "Mt Sunapee",
    img: "./images/mt-sunapee.png",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 69,
    name: "Mountain Creek",
    img: "./images/mountain-creek.jpg",
    state: "New Jersey",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 70,
    name: "Mountain High",
    img: "./images/mountain-high.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1995,
  },
  {
    id: 71,
    name: "Mt Bachelor",
    img: "./images/mt-bachelor.jpg",
    state: "Oregon",
    region: "Northwest",
    country: "US",
    yearPainted: 2019,
  },
  {
    id: 72,
    name: "Mt Buller",
    img: "./images/mt-buller.jpg",
    state: "",
    region: "",
    country: "Australia",
    yearPainted: 1995,
  },
  {
    id: 73,
    name: "Mt Ashland",
    img: "./images/mt-ashland.jpg",
    state: "Oregon",
    region: "Northwest",
    country: "US",
    yearPainted: 2002,
  },
  {
    id: 74,
    name: "Mt Baker",
    img: "./images/mt-baker.jpg",
    state: "Washington",
    region: "Northwest",
    country: "US",
    yearPainted: 1988,
  },
  {
    id: 75,
    name: "Mt Hood Meadows",
    img: "./images/mt-hood-meadows.jpg",
    state: "Oregon",
    region: "Northwest",
    country: "US",
    yearPainted: 2009,
  },
  {
    id: 76,
    name: "Mt Hood Ski Bowl",
    img: "./images/mt-hood-ski-bowl.jpg",
    state: "Oregon",
    region: "Northwest",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 77,
    name: "Mt Rose",
    img: "./images/mt-rose.jpg",
    state: "Nevada",
    region: "Southwest",
    country: "US",
    yearPainted: 2002,
  },
  {
    id: 78,
    name: "Mt Seymour",
    img: "./images/mt-seymour.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2009,
  },
  {
    id: 79,
    name: "Mt Washington",
    img: "./images/mt-washington.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2004,
  },
  {
    id: 80,
    name: "Muju Deogyusan",
    img: "./images/muju-deogyusan.jpg",
    state: "",
    region: "",
    country: "South Korea",
    yearPainted: 1997,
  },
  {
    id: 81,
    name: "Northstar",
    img: "./images/northstar.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2000,
  },
  {
    id: 82,
    name: "Okemo",
    img: "./images/okemo.png",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 2014,
  },
  {
    id: 83,
    name: "Pajarito",
    img: "./images/pajarito.jpg",
    state: "New Mexico",
    region: "Southwest",
    country: "US",
    yearPainted: 2001,
  },
  {
    id: 84,
    name: "Panorama",
    img: "./images/panorama.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2010,
  },
  {
    id: 85,
    name: "Park City",
    img: "./images/park-city.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2015,
  },
  {
    id: 86,
    name: "Pats Peak",
    img: "./images/pats-peak.jpg",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2005,
  },
  {
    id: 87,
    name: "Perisher",
    img: "./images/perisher.jpg",
    state: "",
    region: "",
    country: "Australia",
    yearPainted: 1997,
  },
  {
    id: 88,
    name: "Pico",
    img: "./images/pico.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1997,
  },
  {
    id: 89,
    name: "Powder Mountain",
    img: "./images/powder-mountain.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2011,
  },
  {
    id: 90,
    name: "Powderhorn",
    img: "./images/powderhorn.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2008,
  },
  {
    id: 91,
    name: "Purgatory",
    img: "./images/purgatory.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 92,
    name: "Red Mountain",
    img: "./images/red-mountain.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2007,
  },
  {
    id: 93,
    name: "Red River",
    img: "./images/red-river.jpg",
    state: "New Mexico",
    region: "Southwest",
    country: "US",
    yearPainted: 2010,
  },
  {
    id: 94,
    name: "Revelstoke",
    img: "./images/revelstoke.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2008,
  },
  {
    id: 95,
    name: "Saddleback",
    img: "./images/saddleback.jpg",
    state: "Maine",
    region: "New England",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 96,
    name: "Sierra at Tahoe",
    img: "./images/sierra-at-tahoe.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2000,
  },
  {
    id: 97,
    name: "Silver Mountain",
    img: "./images/silver-mountain.jpg",
    state: "Idaho",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 98,
    name: "Silver Star",
    img: "./images/silver-star.jpg",
    state: "",
    region: "British Columbia",
    country: "Canada",
    yearPainted: 2013,
  },
  {
    id: 99,
    name: "Sipapu",
    img: "./images/sipapu.jpg",
    state: "New Mexico",
    region: "Southwest",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 100,
    name: "Butternut",
    img: "./images/butternut.jpg",
    state: "Massachusetts",
    region: "New England",
    country: "US",
    yearPainted: 2001,
  },
  {
    id: 101,
    name: "Smugglers' Notch",
    img: "./images/smugglers'-notch.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 102,
    name: "Snow Ridge",
    img: "./images/snow-ridge.jpg",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 103,
    name: "Snow Valley",
    img: "./images/snow-valley.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1992,
  },
  {
    id: 104,
    name: "Snowbasin",
    img: "./images/snowbasin.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2005,
  },
  {
    id: 105,
    name: "Snowbird",
    img: "./images/snowbird.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2006,
  },
  {
    id: 106,
    name: "Snowmass",
    img: "./images/snowmass.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1991,
  },
  {
    id: 107,
    name: "Snowshoe",
    img: "./images/snowshoe.jpg",
    state: "West Virginia",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 108,
    name: "Soda Springs",
    img: "./images/soda-springs.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1987,
  },
  {
    id: 109,
    name: "Solitude",
    img: "./images/solitude.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2015,
  },
  {
    id: 110,
    name: "Song Mountain",
    img: "./images/song-mountain.jpg",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2002,
  },
  {
    id: 111,
    name: "Squaw Valley",
    img: "./images/squaw-valley.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2008,
  },
  {
    id: 112,
    name: "Steamboat",
    img: "./images/steamboat.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 113,
    name: "Stevens Pass",
    img: "./images/stevens-pass.jpg",
    state: "Washington",
    region: "Northwest",
    country: "US",
    yearPainted: 1997,
  },
  {
    id: 114,
    name: "Stowe",
    img: "./images/stowe.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 115,
    name: "Stratton",
    img: "./images/stratton.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 116,
    name: "Sugar Bowl",
    img: "./images/sugar-bowl.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 1996,
  },
  {
    id: 117,
    name: "Sugarbush",
    img: "./images/sugarbush.jpg",
    state: "Vermont",
    region: "New England",
    country: "US",
    yearPainted: 1990,
  },
  {
    id: 118,
    name: "Sugarloaf",
    img: "./images/sugarloaf.jpg",
    state: "Maine",
    region: "New England",
    country: "US",
    yearPainted: 2000,
  },
  {
    id: 119,
    name: "Sun Peaks",
    img: "./images/sun-peaks.jpg",
    state: "California",
    region: "Southwest",
    country: "US",
    yearPainted: 2019,
  },
  {
    id: 120,
    name: "Sun Valley",
    img: "./images/sun-valley.jpg",
    state: "Idaho",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2011,
  },
  {
    id: 121,
    name: "Sundance",
    img: "./images/sundance.jpg",
    state: "Utah",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1999,
  },
  {
    id: 122,
    name: "Sunday River",
    img: "./images/sunday-river.jpg",
    state: "Maine",
    region: "New England",
    country: "US",
    yearPainted: 2002,
  },
  {
    id: 123,
    name: "Tamarack",
    img: "./images/tamarack.jpg",
    state: "Idaho",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 2003,
  },
  {
    id: 124,
    name: "Taos",
    img: "./images/taos.jpg",
    state: "New Mexico",
    region: "Southwest",
    country: "US",
    yearPainted: 1993,
  },
  {
    id: 125,
    name: "Telluride",
    img: "./images/telluride.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1998,
  },
  {
    id: 126,
    name: "The Remarkables",
    img: "./images/the-remarkables.jpg",
    state: "",
    region: "",
    country: "New Zealand",
    yearPainted: 1990,
  },
  {
    id: 127,
    name: "Thredbo",
    img: "./images/thredbo.jpg",
    state: "",
    region: "",
    country: "Australia",
    yearPainted: 1994,
  },
  {
    id: 128,
    name: "Timberline",
    img: "./images/timberline.jpg",
    state: "Oregon",
    region: "Northwest",
    country: "US",
    yearPainted: 2007,
  },
  {
    id: 129,
    name: "Treblecone",
    img: "./images/treblecone.jpg",
    state: "",
    region: "",
    country: "New Zealand",
    yearPainted: 2011,
  },
  {
    id: 130,
    name: "Tremblant",
    img: "./images/tremblant.jpg",
    state: "",
    region: "Quebec",
    country: "Canada",
    yearPainted: 2008,
  },
  {
    id: 131,
    name: "Vail",
    img: "./images/vail.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 1988,
  },
  {
    id: 132,
    name: "Valle Nevado",
    img: "./images/valle-nevado.jpg",
    state: "",
    region: "",
    country: "Chile",
    yearPainted: 2008,
  },
  {
    id: 133,
    name: "Wachusett",
    img: "./images/wachusett.jpg",
    state: "Massachusetts",
    region: "New England",
    country: "US",
    yearPainted: 2001,
  },
  {
    id: 134,
    name: "Waterville Valley",
    img: "./images/waterville-valley.jpg",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2016,
  },
  {
    id: 135,
    name: "Whakapapa",
    img: "./images/whakapapa.jpg",
    state: "",
    region: "",
    country: "New Zealand",
    yearPainted: 1988,
  },
  {
    id: 136,
    name: "Whistler Blackcomb",
    img: "./images/whistler-blackcomb.jpg",
    state: "",
    region: "British Cololumbia",
    country: "Canada",
    yearPainted: 1998,
  },
  {
    id: 137,
    name: "White Pass",
    img: "./images/white-pass.jpg",
    state: "Washington",
    region: "Northwest",
    country: "US",
    yearPainted: 2010,
  },
  {
    id: 138,
    name: "Whiteface",
    img: "./images/whiteface.jpg",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2020,
  },
  {
    id: 139,
    name: "Whitefish",
    img: "./images/whitefish.jpg",
    state: "Montana",
    region: "Northern Rockies",
    country: "US",
    yearPainted: 1997,
  },
  {
    id: 140,
    name: "Whitetail",
    img: "./images/whitetail.jpg",
    state: "Pennsylcania",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2009,
  },
  {
    id: 141,
    name: "Wildcat",
    img: "./images/wildcat.jpg",
    state: "New Hampshire",
    region: "New England",
    country: "US",
    yearPainted: 2001,
  },
  {
    id: 142,
    name: "Windham",
    img: "./images/windham.jpg",
    state: "New York",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2005,
  },
  {
    id: 143,
    name: "Winter Park",
    img: "./images/winter-park.jpg",
    state: "Colorado",
    region: "Central Rockies",
    country: "US",
    yearPainted: 2008,
  },
  {
    id: 144,
    name: "Winterplace",
    img: "./images/winterplace.jpg",
    state: "West Virginia",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 1994,
  },
  {
    id: 145,
    name: "Wisp",
    img: "./images/wisp.jpg",
    state: "Maryland",
    region: "Midwest / Mid-Atlantic",
    country: "US",
    yearPainted: 2007,
  },
];

export default resorts;
